apiVersion: v1
kind: Service
metadata:
  name: springboot-starterkit-deployments
spec:
  type: NodePort
  ports:
    - port: 8077
      targetPort: 8077
      protocol: TCP
      nodePort: 31000
  selector:
    app: springboot-starterkit-deployments
